# https://leetcode.com/problems/find-the-difference/

# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

# Example:

# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.


from collections import Counter

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        
        cnt1 = Counter(s)
        cnt2 = Counter(t)
        
        for k,v in cnt2.items():
            if cnt1.get(k) != v:
                return k
        return None
        
        
    def test(self):
        cases = [
            ('', 'a'),
            ('aabcd', 'dbcaak'),
            ('aabcd', 'dbcaad'),
            ('abcd', 'abcde'),
        ]
        for s, t in cases:
            print(s, t, self.findTheDifference(s, t))
            
            
Solution().test()
